cluster:
  name: "cluster"
  node_num: 500
  cards_per_node: 8
  priority: "best fit"    #best fit、big first、best similar
tasks:
  - name: "snt9b"
    path: "data/snt9b/sourceDataSnt9b/*.json"
    save_csv_path: "data/snt9b/csv"
    merge_data_path: "data/snt9b/merge_data.csv"
    useful_data_path: "data/snt9b/useful_data.csv"
    type: multi               #multi、single
  # - name: "mydata"
  #   useful_data_path: "data/mydata/test_data.csv"
  #   type: multi
monitor:
  name: "monitor"
  base_path: "monitor"
  frag_alpha: 0.2
  free_rate_alpha: 0.008
schedulers:
  - name: "FCFS"        #无迁移，无任务暂停
    time_step: 10000
    waitingList:
      wl_priority: "first come first sever"    #cards_big_first、cards_small_first、first come first sever、last come last sever、highters response reatio next、dynamic、short_time_first、long_time_first、lottery            
      wl_alpha: 100       #选择高响应比的时候需要设置的响应系数     
      # wl_migreate_priority: "big first"   #small first、wait list、best fit piece first  
      wl_free_max_rate: 0.8   #选择动态的时候需要设置wl转化的集群空闲率最高阈值
      wl_free_min_rate: 0.1   #选择动态的时候需要设置wl转化的集群空闲率最低阈值
      wl_tasks_num: 500  #选择动态的时候需要设置wl转化的wl任务数量阈值\
    migrateSolver:
      migration_cost_weight: 1.0    #迁移代价的影响权重
      checkpoint_weight: 1.0     #有无checkpoint的影响权重
      load_balance_weight: 1.0    #负载是否均衡的影响权重
logger:
  log_file: "logs/cluster_simulation.log"    
  log_level: "INFO"                          #DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(levelname)s - %(message)s"  
  filemode: "w"
plotter:
  save_path: "figure"
config:
  save_path: "config"

