cluster:
  cards_per_node: 8
  name: cluster
  node_num: 2000
  priority: best fit
config:
  save_path: config
logger:
  filemode: w
  format: '%(asctime)s - %(levelname)s - %(message)s'
  log_file: logs/cluster_simulation.log
  log_level: INFO
monitor:
  base_path: monitor
  frag_alpha: 0.2
  free_rate_alpha: 0.008
  name: monitor
  save_path: monitor/FCFS_Migrate_20241211_210349.json
plotter:
  save_path: figure
schedulers:
- fragment_alpha_rate: 0.005
  migrateSolver:
    checkpoint_weight: 1.0
    load_balance_weight: 1.0
    migration_cost_rate: 0.2
    migration_cost_weight: 1.0
  migrate_times: 1
  name: FCFS_Migrate
  time_step: 3600
  waitingList:
    lottery_max_rate: 0.5
    wl_priority: cards_big_first
tasks:
- merge_data_path: data/snt9b/merge_data.csv
  name: snt9b
  path: data/snt9b/sourceDataSnt9b/*.json
  save_csv_path: data/snt9b/csv
  type: multi
  useful_data_path: data/snt9b/useful_data.csv
timestamp: '20241211_210349'
